// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCh3lzgZ38R-ta3p_yq3orv7ggDhmb390',
    appId: '1:724617878199:web:732f712dfb70ec2f0b4b32',
    messagingSenderId: '724617878199',
    projectId: 'minimal-social-app-fc551',
    authDomain: 'minimal-social-app-fc551.firebaseapp.com',
    storageBucket: 'minimal-social-app-fc551.appspot.com',
    measurementId: 'G-BCGF0L7NQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4XnghPiMxID3L2sGG6vI17EmuKa03Bg',
    appId: '1:724617878199:android:e21e37460e500afc0b4b32',
    messagingSenderId: '724617878199',
    projectId: 'minimal-social-app-fc551',
    storageBucket: 'minimal-social-app-fc551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAvPr5I1fzPmxXW4rONX3XOUwYG8m5rk',
    appId: '1:724617878199:ios:6eae8b97e2c5ec150b4b32',
    messagingSenderId: '724617878199',
    projectId: 'minimal-social-app-fc551',
    storageBucket: 'minimal-social-app-fc551.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAvPr5I1fzPmxXW4rONX3XOUwYG8m5rk',
    appId: '1:724617878199:ios:3e49b9fa81cdda8c0b4b32',
    messagingSenderId: '724617878199',
    projectId: 'minimal-social-app-fc551',
    storageBucket: 'minimal-social-app-fc551.appspot.com',
    iosBundleId: 'com.example.shop.RunnerTests',
  );
}
